# Generated by Django 5.0.2 on 2024-02-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_contact1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTACT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('people', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
    ]
