# Generated by Django 5.0.2 on 2024-02-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIZZA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('range', models.CharField(max_length=200)),
            ],
        ),
    ]
