# Generated by Django 5.0.2 on 2024-02-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='SALADS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('range', models.CharField(max_length=200)),
            ],
        ),
    ]
