# Generated by Django 5.0.2 on 2024-02-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_starter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTACT_INFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/conatact')),
                ('heading', models.CharField(max_length=200)),
                ('caption1', models.CharField(max_length=200)),
                ('caption2', models.CharField(max_length=200)),
                ('cpation3', models.CharField(max_length=200)),
            ],
        ),
    ]
