# Generated by Django 5.0.2 on 2024-03-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.CharField(max_length=200)),
                ('monday', models.CharField(max_length=200)),
                ('tuesday', models.CharField(max_length=200)),
                ('wednesday', models.CharField(max_length=200)),
                ('thurday', models.CharField(max_length=200)),
                ('friday', models.CharField(max_length=200)),
                ('saturday', models.CharField(max_length=200)),
            ],
        ),
    ]
