# Generated by Django 5.0.2 on 2024-03-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAY1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday1', models.CharField(max_length=200)),
                ('sunday2', models.CharField(max_length=200)),
                ('monday1', models.CharField(max_length=200)),
                ('monday2', models.CharField(max_length=200)),
                ('tuesday1', models.CharField(max_length=200)),
                ('tuesday2', models.CharField(max_length=200)),
                ('wednesday1', models.CharField(max_length=200)),
                ('wednesday2', models.CharField(max_length=200)),
                ('thurday1', models.CharField(max_length=200)),
                ('thurday2', models.CharField(max_length=200)),
                ('friday1', models.CharField(max_length=200)),
                ('friday2', models.CharField(max_length=200)),
                ('saturday1', models.CharField(max_length=200)),
                ('saturday2', models.CharField(max_length=200)),
            ],
        ),
    ]
